config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :contacts
  resources :works
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles
  resources :profiles, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :move_to_index, except: [:index, :show]
  
  def index
    @articles = Article.all.order("created_at DESC").page(params[:page]).per(5)  #allは省略可
  end
  
  def new
    @article = Article.new
  end

  def create
    Article.create(title: article_params[:title], text: article_params[:text], image: article_params[:image])
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def edit
    @article = Article.find(params[:id])
        
  end
  
  def update
    article = Article.find(params[:id])
    article.update(article_params)
  end
  
  def destroy
    article = Article.find(params[:id])
    article.destroy
  end

  
  private
  
  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :move_to_top, except: [:show]
  
  def show
    @profile = Profile.find(1)
  end
  
  def edit
    @profile = Profile.find(1)
  end
  
  def update
    profile = Profile.find(1)
    profile.update(profile_params)
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:title, :text, :mini_text, :image)
  end
  
  def move_to_top
    redirect_to controller: :articles, action: :index unless user_signed_in?
  end 
    
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/articles/create.html.erb
<div class="contents-n">  
  <h2>投稿が完了しました。</h2>
  <div class="reture-top">
    <%= link_to "トップへ戻る", root_path, class: 'link-btn' %> 　
  </div>
</div>

app/views/articles/destroy.html.erb
<div class="contents-n">  
  <h2>削除しました。</h2>
  <div class="reture-top">
    <%= link_to "トップへ戻る", root_path, class: 'link-btn' %> 　
  </div>
</div>

app/views/articles/edit.html.erb
<div class="contents-n">  
  <h2>編集</h2>
  <div class="field">
    <%= form_for @article do |f| %>
      <%=f.label ":サムネイル用画像ファイル" %><br>
      <%= f.file_field :image,value: "@article.image", class: "image-form" %><br>
      <br>
      <%= f.label ":タイトル" %><br>
      <%= f.text_field :title, class: "title-form" %><br>
      <br>
      <%= f.label ":本文" %>
      <%= f.hidden_field :text, id: :article_text %>
      <trix-editor input="article_text" value="<%= @article.text %>" class="text-form"></trix-editor>
      <div class="post-article">
        <%= f.submit '更新', class: "submit-btn" %>
      </div>
    <% end %>
  </div>  
</div>

app/views/articles/index.html.erb
<div class="contents-t">
  <div class="article-box">
    <% @articles.each do |article| %>
      <article>
        <div class="article-image-box">
          <% if article.image.attached? %>
            <%= image_tag article.image, class: 'article-image' %>
          <% end %>  
        </div>
        <div class="article-main">
          <div class="article-title-box">
            <h3 class="article-title-t"><%= link_to article.title, article_path(article.id), method: :get, class: 'article-link' %></h3>
            <p class="article-create-t">投稿日:   <%= article.updated_at.strftime('%Y/%m/%d') %>
            <% if user_signed_in? %>
              　　<%= link_to '記事を編集', edit_article_path(article.id), method: :get %>
              <%= link_to '記事を削除', article_path(article.id), method: :delete, data: {confirm: "削除しますか？"} %>
              </p>
            <% end %>
          </div>
          <div class="article-text">
            <%= sanitize article.text, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img del table tr td em br strong div), attributes:  %w(id class href) %>
          </div>
          <div class="article-link-e">
            <%= link_to "記事を読む>>", article_path(article.id), method: :get, class: 'article-link'%>
          </div>
        </div>
      </article>
    <% end %>
    <%= paginate @articles %>
    
  </div>
  
  <div class="sideber">
    <div class="mini-prof">
      <%= image_tag Profile.find(1).image, class: 'profile-image' %>
      <h2><%= link_to  Profile.find(1).name, profile_path(1), class: 'profile-link'%></h2>
      <p class="mini-prof-text">
        <%= simple_format(Profile.find(1).mini_text) %>
      </p>
    </div>
      <a class="twitter-timeline" data-width="280" data-height="500" data-theme="light" href="https://twitter.com/Motoyuki_PinkS?ref_src=twsrc%5Etfw">Tweets by Motoyuki_PinkS</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <% if user_signed_in? %>
      <div class="login-nav">
        <%= link_to '記事投稿', '/articles/new', class: "link-btn" %>
        <%= link_to 'ログアウト', '/users/sign_out', class: "link-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="contents-n">  
  <h2>記事投稿</h2>
  <div class="field">
    <%= form_for @article do |f| %>
      <%=f.label ":サムネイル用画像ファイル" %><br>
      <%= f.file_field :image, class: "image-form" %><br>
      <br>
      <%= f.label ":タイトル" %><br>
      <%= f.text_field :title, class: "title-form" %><br>
      <br>
      <%= f.label ":本文" %>
      <%= f.hidden_field :text, id: :article_text %>
      <trix-editor input="article_text" class="text-form"></trix-editor>
      <div class="post-article">
        <%= f.submit '投稿', class: "submit-btn" %>
      </div>  
    <% end %>
  </div>  
</div>

app/views/articles/show.html.erb
<div class="contents-s">
  <div class="article-s">
    <h1 class="article-title-s"><%= @article.title %></h1>
    <p class="article-create-s">
      投稿日:   <%= @article.updated_at.strftime('%Y/%m/%d') %>
    <% if user_signed_in? %>
      <%= link_to '記事を編集', edit_article_path(@article.id), method: :get %>
      <%= link_to '記事を削除', article_path, method: :delete, data: {confirm: "削除しますか？"} %>
    <% end %>
    </p>
    
    <div class="article-text-s">
      <%= sanitize @article.text, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img del table tr td em br strong div), attributes:  %w(id class href) %>
    </div>
  </div>
  <%= link_to "トップへ戻る", root_path, class: 'top-link' %> 　
</div>

app/views/articles/update.html.erb
<div class="contents-n">  
  <h2>編集が完了しました。</h2>
  <div class="reture-top">
    <%= link_to "トップへ戻る", root_path, class: 'link-btn' %> 　
  </div>
</div>

app/views/contacts/index.html.erb
<div class="contents-s">
  <div class="contacts">
    <p>〇お仕事の依頼、相談はtwitterのDMにてお願いします</p><br>
    <br>
    　　<%= link_to image_tag("Twitter_Logo_WhiteOnBlue", class: 'link-icon'), "https://twitter.com/Motoyuki_PinkS?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Eprofile%3AMotoyuki_PinkS&ref_url=https%3A%2F%2Fintense-headland-91592.herokuapp.com%2F" %>
    <%= link_to "@Motoyuki_PinkS", "https://twitter.com/Motoyuki_PinkS?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Eprofile%3AMotoyuki_PinkS&ref_url=https%3A%2F%2Fintense-headland-91592.herokuapp.com%2F", class: 'twitter-link' %>
  </div>
  <%= link_to "トップへ戻る", root_path, class: 'top-link' %> 　
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motoyuki Sounds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag    'style' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header>
      <img class="logo" src="/assets/logo.PNG" alt="title">
    </header>
    <nav>
      <ul>
        <li class="main-nav"><%= link_to 'Top', '/' %></li>
      　<li class="main-nav"><%= link_to 'Profile', profile_path(1) %></li>
      　<li class="main-nav"><%= link_to 'Works', '/works' %></li>
      　<li class="main-nav"><%= link_to 'Contact', '/contacts' %></li>
      </ul>
    </nav>
    
    <div id="nav-drawer">
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content">
          <li class=""><%= link_to 'Top', '/' %></li>
        　<li class=""><%= link_to 'Profile', profile_path(1) %></li>
        　<li class=""><%= link_to 'Works', '/works' %></li>
        　<li class=""><%= link_to 'Contact', '/contacts' %></li>
      </div>
    </div>
      
    <%= yield %>
    
    <footer>
      <p class="copyright">© 2020 Motoyuki</p>
      
    </footer>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="contents-n">  
  <h2>プロフィール編集</h2>
  <div class="field">
    <%= form_for @profile do |f| %>
      <%=f.label ":プロフィール用画像ファイル" %><br>
      <%= f.file_field :image,value: "@article.image", class: "image-form" %><br>
      <br>
      <%= f.label ":名前" %><br>
      <%= f.text_field :name, class: "title-form" %><br>
      <br>
      <%= f.label ":top用プロフィール文(6行まで)" %><br>
      <%= f.text_area :mini_text, class: 'mini-prof-form' %><br>
      <br>
      <%= f.label ":プロフィール文" %>
      <%= f.hidden_field :text, id: :article_text %>
      <trix-editor input="article_text" value="<%= @profile.text %>" class="text-form"></trix-editor>
      <div class="post-article">
        <%= f.submit '更新', class: "submit-btn" %>
      </div>
    <% end %>
  </div>  
</div>

app/views/profiles/show.html.erb
<div class="contents-s">
  <div class="profile-s">
    <%= image_tag Profile.find(1).image, class: 'profile-image' %>
    <h1 class="profile-name-s"><%= @profile.name %></h1>
    <div class="profile-text-s">
      <%= sanitize @profile.text, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img del table tr td em br strong div), attributes:  %w(id class href) %>
    </div>
  </div>
  <% if user_signed_in? %>
  <div class="edit-profile">
    <%= link_to 'プロフィールを編集', '/profiles/1/edit', class: "link-btn" %>
  </div>
  <% end %>
  <%= link_to "トップへ戻る", root_path, class: 'top-link' %> 　
</div>

app/views/profiles/update.html.erb
<div class="contents-n">  
  <h2>変更が完了しました。</h2>
  <div class="reture-top">
    <%= link_to "トップへ戻る", root_path, class: 'link-btn' %> 　
  </div>
</div>

app/views/works/index.html.erb
<div class="contents-s">
  <div class="works">
    <p>〇下記のサイトにて過去の配信作品をご利用、お聴きいただけます<br>
<br>
<br>
　　<%= link_to image_tag("do-va.jpeg", class: 'link-icon'), "https://dova-s.jp/_contents/author/profile410.html" %><%= link_to "DOVA-SYNDROME 作曲者ページ", "https://dova-s.jp/_contents/author/profile410.html", class: 'works-link' %><br>
<br>
　　<%= link_to image_tag("youtube.png", class: 'link-icon'), "https://www.youtube.com/playlist?list=PL2vyqKNLXiUrNUsMHO6eVvNo2N9N7Clvq" %><%= link_to "YouTube視聴ページ","https://www.youtube.com/playlist?list=PL2vyqKNLXiUrNUsMHO6eVvNo2N9N7Clvq", class: 'works-link' %><br>
<br>
　　<%= link_to image_tag("nico.png", class: 'link-icon'), "http://commons.nicovideo.jp/user/1406089" %><%= link_to "ニコニコモンズ 作品ページ","http://commons.nicovideo.jp/user/1406089", class: 'works-link' %><br>
<br>
<br>
〇その他の制作楽曲などはこちら<br>
<br>
　　<%= link_to image_tag("youtube.png", class: 'link-icon'), "https://www.youtube.com/channel/UCgO3JXdwwnw20KhJavPobrA" %><%= link_to "YouTubeチャンネル「Motoyuki Music channel」","https://www.youtube.com/channel/UCgO3JXdwwnw20KhJavPobrA", class: 'works-link' %><br>
<br>
　　<%= link_to image_tag("sc.png", class: 'link-icon'), "https://soundcloud.com/user-701145389" %><%= link_to "SoundCloud", "https://soundcloud.com/user-701145389", class: 'works-link' %></p>
  </div>  
  <%= link_to "トップへ戻る", root_path, class: 'top-link' %> 　
</div>